services:
  jaeges:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLERTOR_ZIPKIN_HTTP_PORT=:9411
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 9411:9411